setup.py: Package with distutils
We need to include the empty-directory placeholder .gitignores under
example/, for the same reason that we created them for the developer
environment: if they're missing, running the example project crashes
with:

  sqlite3.OperationalError: unable to open database file

because the expected data directory hasn't been created.